### ISSUE TITLE
src.js updated, but injectable.js isn't updated

### ISSUE THREAD

**Issue by hxc4life07** [Blooketware/BlooketUI#10]
Hi, I have seen that the main script has been updated. But i have just seen that the injectable.js file made for blooket utility isn't updated. I think this because the main script was updated 7 hours ago and the injectable was updated some days ago.

**Comment by notzastix** [comment]
I can try to update it, but I have no experience with okr's utility

**Comment by notzastix** [comment]
I tried to get it to work, but i cant
@smintf will have to get it to work

**Comment by smintf** [comment]
Fixed in [Commit 021ec64](https://github.com/Blooketware/BlooketUI/commit/021ec643e59e27bd0f079f34bbf7bcbe168185ea)
