### ISSUE TITLE
[Enhancement] : Reset Crypto Hack

### ISSUE THREAD

**Issue by 3kh0** [Blooketware/BlooketUI#23]
Can you add a hack that in crypto you can set someone else's balance to 0 or something like that? glixxy once had that

**Comment by notzastix** [comment]
i can try, but honestly i have 0 idea of how gliz did it

**Comment by 3kh0** [comment]
> i can try, but honestly i have 0 idea of how gliz did it

can you ask gliz?

**Comment by notzastix** [comment]
> > i can try, but honestly i have 0 idea of how gliz did it
> 
> can you ask gliz?

he hates me

**Comment by notzastix** [comment]
> from my POV, it just asked who you want (john) to reset and it sends a request saying that the user took all of john's crypto

it uses firebase websockets, i figured out how
