### ISSUE TITLE
Mobile Compatibility.

### ISSUE THREAD

**Issue by coolman3289** [Blooketware/BlooketUI#3]
Plea please please, be the first blooket hack dev that is mobile compatable. Sell dupes does not work and others too for mobile.

**Comment by smintf** [comment]
huh ig i could look into it.

**Comment by hxc4life07** [comment]
Hi sminf. I think that other compatibility for mobiles could be the option of draging the menu and also hide and show it up again without refreshing the blooket utility (thatfrueddued) or without using bookmarklet again. 
Thank you for recreating this javascript snippets of the blooket "hacks"

**Comment by coolman3289** [comment]
I just want something.

**Comment by smintf** [comment]
> Hi sminf. I think that other compatibility for mobiles could be the option of draging the menu and also hide and show it up again without refreshing the blooket utility (thatfrueddued) or without using bookmarklet again. Thank you for recreating this javascript snippets of the blooket "hacks". And also thanks for taking this libro account to update the multitool 👍

i could for example make it automatically show when u tap on a certain part of the screen

**Comment by smintf** [comment]
> I just want something.

as for the hacks not working i'd also like you to specify the exact ones that *don't* work.

**Comment by hxc4life07** [comment]
> > Hi sminf. I think that other compatibility for mobiles could be the option of draging the menu and also hide and show it up again without refreshing the blooket utility (thatfrueddued) or without using bookmarklet again. Thank you for recreating this javascript snippets of the blooket "hacks". And also thanks for taking this libro account to update the multitool 👍
> 
> i could for example make it automatically show when u tap on a certain part of the screen

Oh, that would be a great idea.

**Comment by coolman3289** [comment]
Also thank you so much for working on mobile support, you did way more than all the other blooket hack developers for mobile.

**Comment by coolman3289** [comment]
I know for sure all tower hacks work on single player

**Comment by coolman3289** [comment]
Also are you going to obfuscate this. I think you should so blooket that’s a harder time cracking this.

**Comment by coolman3289** [comment]
@smintf

**Comment by TheVillainCoder** [comment]
@coolman3289 be patient how do you know his time zone?

**Comment by coolman3289** [comment]
Ur right sorry.

**Comment by smintf** [comment]
> Also are you going to obfuscate this. I think you should so blooket that’s a harder time cracking this.

This would entirely defeat the point of hosting this on github.

**Comment by smintf** [comment]
> > > Hi sminf. I think that other compatibility for mobiles could be the option of draging the menu and also hide and show it up again without refreshing the blooket utility (thatfrueddued) or without using bookmarklet again. Thank you for recreating this javascript snippets of the blooket "hacks". And also thanks for taking this libro account to update the multitool 👍
> > 
> > 
> > i could for example make it automatically show when u tap on a certain part of the screen
> 
> This I don’t mind because I have keyboard on my iPad, but maybe minimize it (like turn it into ur logo and mini) and make it draggable and put on side, and when clicked opens. This does not happen when you click “e” only when you click the minus.

this would more or less be more practical, as i could use the user agent to determine whether its a mobile device or not and then spawn the button accordingly.

**Comment by smintf** [comment]
> @smintf you did a great job with everything except with auto-anwser. Don’t know if this is just mobile, but using the bookmarklet method (don’t know about non-bookmarklet) it does this: ![22387594-7ECD-478B-A0AE-637668CE8ED3](https://user-images.githubusercontent.com/64605756/164041063-14c68aec-0195-4b31-95af-b6990383faa8.png)

no thats intended as what it basically does is modify the question data itself and in this case makes all the options correct and changes the question text aswell.

**Comment by hxc4life07** [comment]
That has a lot of sense.

**Comment by notzastix** [comment]
> @smintf you did a great job with everything except with auto-anwser. Don’t know if this is just mobile, but using the bookmarklet method (don’t know about non-bookmarklet) it does this: ![22387594-7ECD-478B-A0AE-637668CE8ED3](https://user-images.githubusercontent.com/64605756/164041063-14c68aec-0195-4b31-95af-b6990383faa8.png)

this broke sometimes bcuz it was using gliz's stuff and that just doesn't work when he updates,
I coded a custom version
