### ISSUE TITLE
Says spam open  and auto sell are outdated

### ISSUE THREAD

**Issue by coolman3289** [Blooketware/BlooketUI#31]
Pls fix

**Comment by coolman3289** [comment]
@smintf @3kh0

**Comment by smintf** [comment]
Fixed by [Commit 0b764b8](https://github.com/Blooketware/BlooketUI/commit/0b764b8c1425b8e4fe989a14dfc375e17d6c9c9e).

**Comment by Doob123123** [comment]
It still has the same error message
