### ISSUE TITLE
[Bug] : Out of date code

### ISSUE THREAD

**Issue by zek-c** [Blooketware/BlooketUI#34]
### What device do you use?

chromebook

### What browser do you use?

chrome

### Describe the error in detail.

Spam open boxes and auto sell dupes doesnt work, also the cafe ones dont work

**Comment by zek-c** [comment]
pls fix

**Comment by zek-c** [comment]
pls fix 🤬

**Comment by coolman3289** [comment]
It fixed

**Comment by coolman3289** [comment]
Get the current version

**Comment by smintf** [comment]
> pls fix 🤬

It's fixed for god's sake, just get the latest version.
