### ISSUE TITLE
[Bug] : yall said it was fixed it still dont work

### ISSUE THREAD

**Issue by zek-c** [Blooketware/BlooketUI#35]
### What device do you use?

chromebook

### What browser do you use?

chrome

### Describe the error in detail.

heres the video it might be trash bc its chromebook bro why is it orange

https://user-images.githubusercontent.com/105883248/169701531-47b01465-6618-4a37-a920-db307279227c.mp4

**Comment by zek-c** [comment]
btw i was just showing you the other ones work

**Comment by zek-c** [comment]
oh and i played with the code a lil dont mind the window alert

**Comment by notzastix** [comment]
It's cuz their skidding gliz' code instead of coding a custom box opener.

**Comment by smintf** [comment]
Fixed in [60cda81](https://github.com/Blooketware/BlooketUI/commit/60cda817ab2b37ab033c5e918afb254dc29cbc4d)
