### ISSUE TITLE
Outdated scripts

### ISSUE THREAD

**Issue by coolman3289** [Blooketware/BlooketUI#36]
The scripts like spam open boxes are outdated again. I have the newest bookmarklet. @smintf @3kh0

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 can I have it?

**Comment by coolman3289** [comment]
@Snowflake-Coder-H2o

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 Can I have the updated bookmarklet?

**Comment by coolman3289** [comment]
> 

I don’t have it

**Comment by coolman3289** [comment]
If I did I would do myself
@Snowflake-Coder-H2o

**Comment by Snowflake-Coder-H2o** [comment]
> The scripts like spam open boxes are outdated again. I have the newest bookmarklet. @smintf @3kh0

You said " I have the newest bookmarklet"

**Comment by Snowflake-Coder-H2o** [comment]
O ok

**Comment by Snowflake-Coder-H2o** [comment]
NO idea

**Comment by Orangenal-name** [comment]
Injectable doesn't work either

**Comment by Snowflake-Coder-H2o** [comment]
@smintf @3kh0 bro fix this rn. Yours things arent up to date

**Comment by 3kh0** [comment]
@Snowflake-Coder-H2o we are working this

**Comment by xSekN** [comment]
yeah almost none of them work

**Comment by nickhanke6969** [comment]
@3kh0 do you know when the issue will be fixed

**Comment by smintf** [comment]
Fixed in [60cda81](https://github.com/Blooketware/BlooketUI/commit/60cda817ab2b37ab033c5e918afb254dc29cbc4d)
