### ISSUE TITLE
[Enhancement] : Add Deceptive Dinos cheats?

### ISSUE THREAD

**Issue by fo-od** [Blooketware/BlooketUI#37]
### What device do you use?

Chromebook

### What browser do you use?

Chrome

### Describe the error in detail.

(not an error) maybe try to add any hacks for this gamemode, like esp without having to click the built in cheat button, and maybe see for investigate make a hack to see who just cheated so you know who cheated

**Comment by Orangenal-name** [comment]
definitely need a choice esp, maybe if it's possible add an esp to see if someone has cheated before you investigate them?

**Comment by fo-od** [comment]
^^^ this

**Comment by smintf** [comment]
done in [15e787d](https://github.com/Blooketware/BlooketUI/commit/15e787d559aa55ba69b19f1085d4d6535ab4df7c)
