### ISSUE TITLE
[FEATURE] Block blooketsecurity.com

### ISSUE THREAD

**Issue by some-du6e** [Blooketware/BlooketUI#39]
A thing while i was making my hack (not a hack but a multitool of some sort) is that i found a error which said
![Screen Shot 2022-06-16 at 1 35 22 PM](https://user-images.githubusercontent.com/103129948/174154407-9a4bffbe-605f-4f4d-974a-86746c2a49a4.png)
First thing i saw that it was trying to report me or something. So can you block it or something?

**Comment by notzastix** [comment]
can i ask what u where doing when it showed that?, cause csp-report is trying to access a site outside of blooket.com and its subdomains

**Comment by smintf** [comment]
> A thing while i was making my hack (not a hack but a multitool of some sort) is that i found a error which said ![Screen Shot 2022-06-16 at 1 35 22 PM](https://user-images.githubusercontent.com/103129948/174154407-9a4bffbe-605f-4f4d-974a-86746c2a49a4.png) First thing i saw that it was trying to report me or something. So can you block it or something?

can only be done with an extension ¯\\_(ツ)_/¯

**Comment by notzastix** [comment]
> > A thing while i was making my hack (not a hack but a multitool of some sort) is that i found a error which said ![Screen Shot 2022-06-16 at 1 35 22 PM](https://user-images.githubusercontent.com/103129948/174154407-9a4bffbe-605f-4f4d-974a-86746c2a49a4.png) First thing i saw that it was trying to report me or something. So can you block it or something?
> 
> can only be done with an extension ¯\_(ツ)_/¯

u can do it by overriding fetch, as shown in some of qaiiks scripts
