### ISSUE TITLE
[Bug] : spam open boxes not working

### ISSUE THREAD

**Issue by Orangenal-name** [Blooketware/BlooketUI#42]
### What device do you use?

Windows 10 PC

### What browser do you use?

Opera GX

### Describe the error in detail.

When using spam open boxes, it doesn't appear to do anything. Upon looking in the console, it gives this error: 
![image](https://user-images.githubusercontent.com/44399774/174662981-bba879c2-2494-4f8c-87e8-372e271217eb.png)

**Comment by notzastix** [comment]
probably some type of input error, let's see if @smintf fixes it or just steals gliz's spam open boxes

**Comment by 3kh0** [comment]
@notzastix can you look into this?

**Comment by notzastix** [comment]
> @notzastix can you look into this?

sure

**Comment by notzastix** [comment]
> ### What device do you use?
> Windows 10 PC
> 
> ### What browser do you use?
> Opera GX
> 
> ### Describe the error in detail.
> When using spam open boxes, it doesn't appear to do anything. Upon looking in the console, it gives this error: ![image](https://user-images.githubusercontent.com/44399774/174662981-bba879c2-2494-4f8c-87e8-372e271217eb.png)

seems to work fine for me, are you still having this issue?

**Comment by 3kh0** [comment]
I don't have this issue

**Comment by Orangenal-name** [comment]
> seems to work fine for me, are you still having this issue?

It works now, I guess it was accidentally fixed? Oh well, at least it works now
