### ISSUE TITLE
[Bug] : Set money/crypto kicks you from the game

### ISSUE THREAD

**Issue by FinnyMarigold58** [Blooketware/BlooketUI#43]
### What device do you use?

PC

### What browser do you use?

Brave

### Describe the error in detail.

When you use the set money/crypto the page redirects you to https://dashboard.blooket.com/play

**Comment by FinnyMarigold58** [comment]
Also could you make it so the cafe set money doesn't just remove your money, so you can at least get 1st

**Comment by Orangenal-name** [comment]
this is a duplicate of #16

**Comment by FinnyMarigold58** [comment]
> this is a duplicate of #16
