### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by 3kh0** [Blooketware/BlooketUI#6]
For some of the cheats, they use different functions like `window.alert`, `window.prompt`, and `window.confirm`, blooket has found ways to detect them and disable your account, could you find a way around this? I am already on my 3rd account.

**Comment by coolman3289** [comment]
3rd account because of this cheat or in general?

**Comment by smintf** [comment]
> For some of the cheats, they use different functions like `window.alert`, `window.prompt`, and `window.confirm`, blooket has found ways to detect them and disable your account, could you find a way around this? I am already on my 3rd account.

Huh, that shouldn't be a problem as my script overrides the `window.alert`, `window.prompt` and `window.confirm` functions.

**Comment by smintf** [comment]
> For some of the cheats, they use different functions like `window.alert`, `window.prompt`, and `window.confirm`, blooket has found ways to detect them and disable your account, could you find a way around this? I am already on my 3rd account.

i could maybe replace the `window.*` functions with a third party javascript library, but injecting one is highly impractical.

**Comment by smintf** [comment]
i just checked whether my bypass still works and it seems to hold up.
![image](https://user-images.githubusercontent.com/46701284/164156071-b99cac59-3bcc-447e-b314-de8c291cdf1d.png)

**Comment by notzastix** [comment]
> For some of the cheats, they use different functions like `window.alert`, `window.prompt`, and `window.confirm`, blooket has found ways to detect them and disable your account, could you find a way around this? I am already on my 3rd account.

There is a known bypass for this using iframes mentioned by @smintf and that everyone is using.
I looked through Blooket's code a bit ago and nothing is new on the window.alert(), window.prompt() or window.confirm() patch.

I will make sure to update our bypass if anything changes or more checks are added
