### ISSUE TITLE
[Bug] : No name detected

### ISSUE THREAD

**Issue by GustyCube** [Blooketware/BlooketUI#75]
### What device do you use?

Mac

### What browser do you use?

Chrome

### Describe the error in detail.

When I used the hacks, the username was null. That meant I couldn't use some of the first options.

**Comment by s-aarchen** [comment]
same here :( Please fix this

**Comment by GustyCube** [comment]
This has to do with Blooket cracking down on hacks. They are blocking requests to api.blooket.com, which all hacks are rooted to. I am not sure if there are any working hacks anymore, but I can try to fix it.

**Comment by arandomhooman** [comment]
Yeah,that would be appreciated by those who are in the Blooket community.
