### ISSUE TITLE
Sometime on mobile (maybe desktop too) you cant exit the gui

### ISSUE THREAD

**Issue by coolman3289** [Blooketware/BlooketUI#8]
Pressing E or - or x does nothing. If press - and x it blinks (the buttons) but nothing else happens.

**Comment by 3kh0** [comment]
That does happen to me sometimes!

**Comment by smintf** [comment]
> Pressing E or - or x does nothing. If press - and x it blinks (the buttons) but nothing else happens.

This is mostly likely due to the fact the you either tried running the hack multiple times without refreshing the page or it could be caused the by the event listeners not being properly attached.

**Comment by coolman3289** [comment]
The first.
