### ISSUE TITLE
[Enhancement] : Cheats for Blook Rush

### ISSUE THREAD

**Issue by coolman3289** [Blooketware/BlooketUI#9]
That would be awesome.

**Comment by coolman3289** [comment]
And tower of doom.

**Comment by notzastix** [comment]
I'll look into it when I get on my pc
I know that blookrush had some extra checks though

**Comment by smintf** [comment]
> And tower of doom.

Tower of Doom has cheats.

**Comment by coolman3289** [comment]
@smintf 
![Uploading A7382A09-7759-4088-A8A8-435CFF2A2F48.png…]()

**Comment by smintf** [comment]
Your image isn't being displayed? mind reuploading it?

**Comment by coolman3289** [comment]
@smintf 
![4EC429D7-5EB8-48CB-9516-9B052FEFB35F](https://user-images.githubusercontent.com/64605756/164529004-b00453ed-1320-4c96-9c53-d7ac345e108c.png)
![3E17D6D1-3DD4-4E58-8FE9-D5EA74B97AEB](https://user-images.githubusercontent.com/64605756/164529008-3fa2868b-a9fa-46c2-bf05-63fec3dbe7cd.png)

**Comment by smintf** [comment]
That is most likely a bug.

**Comment by smintf** [comment]
Which causes it to not detect the current gamemode.

**Comment by coolman3289** [comment]
@smintf Why did you delete my comment …. Anyway, can you attempt to fix it.

**Comment by coolman3289** [comment]
Oh it showed my username

**Comment by smintf** [comment]
> @smintf Why did you delete my comment …. Anyway, can you attempt to fix it.

yes.

**Comment by smintf** [comment]
added in [15e787d](https://github.com/Blooketware/BlooketUI/commit/15e787d559aa55ba69b19f1085d4d6535ab4df7c)
